name: Build Docker Image

on:
  push:
    paths:
      - Dockerfile
      - entrypoint.sh

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Login to ghcr.io
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/slashnephy/rclone-watch:latest
